@startuml [Component Item] Relace
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.3.0
!define ICONURL2 https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites

!includeurl ICONURL/devicons/nodejs_small.puml
!includeurl ICONURL/devicons/react.puml
!includeurl ICONURL/devicons/mongodb.puml

AddRelTag("default", $lineStyle=DashedLine())
AddRelTag("abstract", $lineStyle=DottedLine(), $lineColor="blue")

Container(client, "Single Page Application", "React", "The client web applications user interact with", "react")

Container_Boundary(item, "Item Service"){
    
}
ContainerDb(itemdb, "Item Database", "MongoDB", "Database for storing user credentials", "mongodb")

@enduml