apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
        - name: item
          image: deanarchy/item
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: DB_URI
              value: "mongodb://item-mongo-service:27017/item"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: AMQP_URL
              value: "amqp://rabbitmq-service"
      initContainers:
        - name: init-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -vzw 2 rabbitmq-service 15672; do echo waiting rabbitmq service to woke; sleep 2; done",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
spec:
  selector:
    app: item
  ports:
    - name: item
      protocol: TCP
      port: 3000
      targetPort: 3000
