apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: deanarchy/payment
          resources:
            limits:
              memory: "512Mi"
          env:
            - name: DB_URI
              value: "mongodb://payment-mongo-service:27017/payment"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-key
                  key: STRIPE_KEY
            - name: AMQP_URL
              value: "amqp://rabbitmq-service"
      initContainers:
        - name: init-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -vzw 2 rabbitmq-service 15672; do echo waiting rabbitmq service to woke; sleep 2; done",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
    - name: payment
      protocol: TCP
      port: 3000
      targetPort: 3000
